login/urls.py
#conding=utf-8


from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index_view, name="login"),
    path('register/',views.register_view, name="register"),
    path('logout/', views.logout, name='logout'),
    path('user/',views.user_view, name="user")
]

mynews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from news.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('news/', include('news.urls', namespace='news')),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('login/',include('login.urls', namespace='login')),
]

news/urls.py
# coding=utf-8
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:new_id>', views.detail, name='detail'),
    path('search_news/<int:num>', views.find_new, name='search_news'),
    path('inlandnews/<int:num>', views.inlandnews, name='inland'),
    path('outlandnews/<int:num>', views.outlandnews, name='outland'),
    path('hotspotnews/<int:num>', views.hotspotnews, name='hotspot'),
]

login/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import logout, authenticate
from django.db import models

# Create your models here.


class MyUser(AbstractUser):

    class Meta:
        verbose_name = '用户'

login/forms.py
# coding=utf-8
from builtins import len

from django import forms
from django.contrib.auth.models import User
import re
from django.contrib.auth import get_user_model
User = get_user_model()

def email_check(email):
    pattern = re.compile(r"\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?")
    return re.match(pattern, email)


class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50)
    email = forms.EmailField(label='Email', )
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)

    # Use clean methods to define custom validation rules

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if len(username) < 6:
            raise forms.ValidationError("你的用户名必须超过6位！")
        elif len(username) > 50:
            raise forms.ValidationError("你的用户名太长，不能超过25个字！")
        else:
            filter_result = User.objects.filter(username__exact=username)
            if len(filter_result) > 0:
                raise forms.ValidationError("你的用户名已存在！")

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email_check(email):
            filter_result = User.objects.filter(email__exact=email)
            if len(filter_result) > 0:
                raise forms.ValidationError("你的邮箱已存在！")
        else:
            raise forms.ValidationError("请输入一个有效的邮箱！")

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if len(password1) < 6:
            raise forms.ValidationError("你的密码太短了，不能小于6位！")
        elif len(password1) > 20:
            raise forms.ValidationError("你的密码太长了，不能超过20位！")

        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("两次输入的密码不一致，请重试！")

        return password2


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    # Use clean methods to define custom validation rules

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if email_check(username):
            filter_result = User.objects.filter(email__exact=username)
            if not filter_result:
                raise forms.ValidationError("该邮箱不存在！")
        else:
            filter_result = User.objects.filter(username__exact=username)
            if not filter_result:
                raise forms.ValidationError("这个用户名不存在，请先注册！")

        return username

login/views.py
from django.contrib import auth
from django.shortcuts import render, reverse, redirect

from login.forms import RegistrationForm, LoginForm
from news.models import history, News
from .models import MyUser

from django.contrib.auth import get_user_model
User = get_user_model()
# 处理注册功能
def register_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password2']

            # 使用内置User自带create_user方法创建用户，不需要使用save()
            new_user = User.objects.create_user(username=username, password=password, email=email)
            new_user.save()

            # 如果直接使用objects.create()方法后不需要使用save()
            return redirect(reverse("login:login"), {'all': all})

    else:
        form = RegistrationForm()

    return render(request, 'register.html', {'form': form})


# 处理登录功能，渲染登录首页
def index_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = auth.authenticate(username=username, password=password)

            if user is not None and user.is_active:
                # 将username写入session，存入服务器
                auth.login(request, user)
                request.session['username'] = username
                # return redirect(reverse("index"), {'username':username, 'is':is_login})
                # return HttpResponseRedirect(reverse('index'))
                obj = redirect('index')
                return  obj

            else:
            # 登陆失败
                return render(request, 'login.html', {'form': form,'message': '密码错误，请重试！'})

    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})


# 用户退出
def logout(request):
        auth.logout(request)
        return redirect(reverse("index"))


# 获取用户信息及历史浏览
def user_view(request):
    user = request.user
    a = request.user.id
    b = history.objects.filter(user_id=a).order_by('-time')

    return render(request, 'history.html', { "b" : b , "a" : user})

templates/base.html
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    {% block css %}{% endblock %}

</head>
<body>
{% block content %}{% endblock %}
{% block contentOther %}{% endblock%}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
{% block script %}{% endblock %}
</body>
</html>

templates/find.html
{#新闻搜索结果页#}
{% extends 'navicate.html' %}
{% load static %}
{% block contentOther %}
    <div class="col-8">
        <div class="list-group">
            {% if not data %}
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <h1 class="display-4">Not Found</h1>
                        <p class="lead">没有找到相关新闻</p>
                    </div>
                </div>
            {% else %}
                {% for i in postList %}
                    <a href="{% url 'news:detail' i.id %}" class="list-group-item list-group-item-action d-flex w-100">
                        <div class="mr-2">
                            <img src="/{{ MEDIA_URL }}{{ i.pic }}" width=100 height=50>
                        </div>
                        <div class="flex-fill">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1 font-weight-bold">{{ i.title }}</h5>
                                <small class="text-muted">{{ i.publish_data}}</small>
                            </div>
                            <p class="mb-1 text-truncate"></p>
                        </div>
                    </a>
                {% endfor %}
            {% endif %}
        </div>

        <nav id="page-nav">
                {% if postList.has_previous %}
                    <a class="extend prev" rel="next" href="{% url 'news:search_news' postList.previous_page_number %}">« Prev</a>
                {% endif %}
                {% for page in pageList %}
                    {% if currentNum == page %}
                        <span class="page-number current">{{ page }}</span>
                    {% else %}
                        <a class="page-number" href="{% url 'news:search_news' page %}">{{ page }}</a>
                    {% endif %}
                {% endfor %}
                {% if postList.has_next %}
                    <a class="extend next" rel="next" href="{% url 'news:search_news' postList.next_page_number %}">Next »</a>
                {% endif %}
            </nav>
    </div>
{% endblock %}

templates/history.html
{#历史记录#}
{% extends 'navicate.html' %}
{% load static %}
{% block contentOther %}
    <div class="row mt-4">
        <div class="col-8">
            <div class="list-group">
                {% if not b %}
                    <div class="jumbotron jumbotron-fluid">
                        <div class="container">
                            <h1 class="display-4">Not Found</h1>
                            <p class="lead">没有历史记录</p>
                        </div>
                    </div>
                {% else %}
                    {% for i in b %}
                        <a href="{% url 'news:detail' i.new.id %}" class="list-group-item list-group-item-action d-flex w-100">
                            <div class="mr-2">
                                <img src="/{{ MEDIA_URL }}{{ i.new.pic }}" width=100 height=50>
                            </div>
                            <div class="flex-fill">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1 font-weight-bold">{{ i.new.title }}</h5>
                                    <small class="text-muted">{{ i.time }}</small>
                                </div>
                                <p class="mb-1 text-truncate"></p>
                            </div>
                        </a>
                    {% endfor %}
                {% endif %}

            </div>
        </div>
        <div>
            <ul class="list-group">
            <li class="list-group-item">当前用户：{{ a.username }}</li>
            <li class="list-group-item">用户邮箱：{{ a.email }}</li>
            </ul>
        </div>
    </div>
{% endblock %}

templates/hotspotnews.html
{#热点新闻结果页#}
{% extends 'navicate.html' %}
{% load static %}
{% block hot %}
    text-primary disabled
{% endblock hot %}
{% block contentOther %}
    <div class="col-8">
        <div class="list-group">
            {% if not data %}
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <h1 class="display-4">Not Found</h1>
                        <p class="lead">没有相关新闻</p>
                    </div>
                </div>
            {% else %}
                {% for i in postList %}
                    <a href="{% url 'news:detail' i.id %}" class="list-group-item list-group-item-action d-flex w-100">
                        <div class="mr-2">
                            <img src="/{{ MEDIA_URL }}{{ i.pic }}" width=100 height=50>
                        </div>
                        <div class="flex-fill">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1 font-weight-bold">{{ i.title }}</h5>
                                <small class="text-muted">{{ i.publish_data}}</small>
                            </div>
                            <p class="mb-1 text-truncate"></p>
                        </div>
                    </a>
                {% endfor %}
            {% endif %}
        </div>

        <nav id="page-nav">
                {% if postList.has_previous %}
                    <a class="extend prev" rel="next" href="{% url 'news:hotspot' postList.previous_page_number %}">« Prev</a>
                {% endif %}
                {% for page in pageList %}
                    {% if currentNum == page %}
                        <span class="page-number current">{{ page }}</span>
                    {% else %}
                        <a class="page-number" href="{% url 'news:hotspot' page %}">{{ page }}</a>
                    {% endif %}
                {% endfor %}
                {% if postList.has_next %}
                    <a class="extend next" rel="next" href="{% url 'news:hotspot' postList.next_page_number %}">Next »</a>
                {% endif %}
            </nav>
    </div>
{% endblock %}

templates/index.html
{# 首页轮播和新闻标题展示 #}
{% extends 'navicate.html' %}
{% load static %}
{% block title %}首页{% endblock %}
{% block css %}
    <style>
        .banner {
            max-width: 1000px;
            margin: 0 auto;
            max-height: 500px;
        }

        .my-badge {
            top: .75rem;
            left: 1.25rem;
        }
    </style>
{% endblock %}
{% block Index %}
    text-primary disabled
{% endblock Index %}
{% block contentOther %}
    <div id="carouselExampleCaptions" class="carousel slide banner" data-ride="carousel">>
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <a href="{% url 'news:detail' t1.id %}">
                        <img src="{{ MEDIA_URL }}{{ t1.pic }}" class="d-block w-100" width="800px" height="400px" alt="...">
                </a>
                <div class="carousel-caption d-none d-md-block">
                    <p>{{ t1.title }}</p>
                </div>
            </div>
            <div class="carousel-item">
                <a href="{% url 'news:detail' t2.id %}">
                    <img src="{{ MEDIA_URL }}{{ t2.pic }}" class="d-block w-100" width="800px" height="400px" alt="...">
                </a>
                <div class="carousel-caption d-none d-md-block">
                    <p>{{ t2.title }}</p>
                </div>
            </div>
            <div class="carousel-item">
                <a href="{% url 'news:detail' t3.id %}">
                    <img src="{{ MEDIA_URL }}{{ t3.pic }}" class="d-block w-100" width="800px" height="400px" alt="...">
                </a>
                <div class="carousel-caption d-none d-md-block">
                    <p>{{ t3.title }}</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">上一个</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">下一个</span>
        </a>
    </div>
    <div class="row mt-4">
        <div class="col-8">
            <div class="list-group">
                {% for top in t_list %}
                    <a href="{% url 'news:detail' top.id %}"
                       class="list-group-item list-group-item-action d-flex w-100">
                        <div class="mr-2">
                            <img src="{{ MEDIA_URL }}{{ top.pic }}" width=100 height=50>
                            <span class="badge badge-secondary my-badge position-absolute badge-danger">推荐</span>
                        </div>
                        <div class="flex-fill">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1 font-weight-bold">{{ top.title }}</h5>
                                <small class="text-muted">{{ top.publish_data }}</small>
                            </div>
                            <p class="mb-1 text-truncate"></p>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>

        <div class="col-4">
            <div class="list-group">
                {% for top in top_list %}
                    <li class="list-group-item">
                        <span class="badge badge-secondary badge-danger">Hot</span>
                        <a class="text-decoration-none" href="{% url 'news:detail' top.id %}">{{ top.title }}</a>
                    </li>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock contentOther %}

templates/inlandnews.html
{#国内新闻结果页#}
{% extends 'navicate.html' %}
{% load static %}
{% block home %}
    text-primary disabled
{% endblock home %}
{% block contentOther %}
    <div class="col-8">
        <div class="list-group">
            {% if not data %}
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <h1 class="display-4">Not Found</h1>
                        <p class="lead">没有相关新闻</p>
                    </div>
                </div>
            {% else %}
                {% for i in postList %}
                    <a href="{% url 'news:detail' i.id %}" class="list-group-item list-group-item-action d-flex w-100">
                        <div class="mr-2">
                            <img src="/{{ MEDIA_URL }}{{ i.pic }}" width=100 height=50>
                        </div>
                        <div class="flex-fill">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1 font-weight-bold">{{ i.title }}</h5>
                                <small class="text-muted">{{ i.publish_data}}</small>
                            </div>
                            <p class="mb-1 text-truncate"></p>
                        </div>
                    </a>
                {% endfor %}
            {% endif %}


            <nav id="page-nav">
                {% if postList.has_previous %}
                    <a class="extend prev" rel="next" href="{% url 'news:inland' postList.previous_page_number %}">« Prev</a>
                {% endif %}
                {% for page in pageList %}
                    {% if currentNum == page %}
                        <span class="page-number current">{{ page }}</span>
                    {% else %}
                        <a class="page-number" href="{% url 'news:inland' page %}">{{ page }}</a>
                    {% endif %}
                {% endfor %}
                {% if postList.has_next %}
                    <a class="extend next" rel="next" href="{% url 'news:inland' postList.next_page_number %}">Next »</a>
                {% endif %}
            </nav>
        </div>
    </div>
{% endblock %}

templates/login.html
{# 登录功能实现 #}
{% extends 'navicate.html' %}
{% load static %}
{% block title %}登录{% endblock %}
{% block contentOther %}
    <div align="center">
        <h2>Login</h2>
        {% if message %}
         {{ message }}
        {% endif %}
        <div class="form-wrapper">
           <form method="post" action="{% url 'login:login' %}" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
                   <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                     <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
                   </div>
                {% endfor %}
              <div class="button-wrapper submit">
                 &emsp;&emsp;&emsp;&emsp;<input type="submit" value="登录" />&emsp;&emsp;<button><a href="{% url 'login:register' %}">注册</a>
              </div>
           </form>
        </div>
    </div>

{% endblock contentOther %}

{#        <form action="{% url 'login:login' %}" method="post">#}
{#            {% csrf_token %}#}
{#            <div class="form-group">#}
{#                <label for="exampleInputEmail1">用户名：</label><input type="text" name="name" required/>#}
{#                <small id="emailHelp" class="form-text text-muted">请正确填写你的用户名</small>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <label for="exampleInputPassword1">密&emsp;码：</label><input type="password" name="pwd" required/>#}
{#            </div>#}
{#            <p>#}
{#                &emsp;&emsp;<input type="submit" value="登录"/>&emsp;&emsp;<button><a href="{% url 'login:register' %}">注册</a>#}
{#            </button>#}
{#            </p>#}
{#        </form>#}

templates/navicate.html
{# 主页标题栏 #}
{% extends 'base.html' %}
{% load static %}
{% block title %}首页{% endblock %}
{% block css %}{% endblock %}
{% block content %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="mr-2">
            <a href="{% url 'index' %}">
                <img src="{% static 'images/logo.jpg' %}" width=75 height=75>
            </a>
        </div>
        <a class="navbar-brand" href="{% url 'index' %}">新闻管理系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link {% block Index %}{% endblock Index%}" href="{% url 'index' %}">主页<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% block home %}{% endblock home%}">
                    <a class="nav-link" href="{% url 'news:inland' 1%}">国内新闻<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% block foreign  %}{% endblock foreign %}">
                    <a class="nav-link" href="{% url 'news:outland' 1 %}">国际时事</a>
                </li>
                <li class="nav-item {% block hot %}{% endblock hot%}">
                    <a class="nav-link" href="{% url 'news:hotspot' 1 %}">新闻热点</a>
                </li>
            </ul>
            {% if user.is_authenticated %}
                <button><a href="{% url 'login:user' %}">浏览历史</a></button>&emsp;
                <button><a href="{% url 'login:logout' %}">登出</a></button>&emsp;
            {% else %}
                <button><a href="{% url 'login:login' %}">登录</a></button>&emsp;
            {% endif %}
{#                <button><a href="{% url 'login:user' %}">浏览历史</a></button>&emsp;<button><a href="{% url 'login:login' %}">登录</a></button>&emsp;<button><a href="{% url 'news:logout' %}">登出</a></button>&emsp;#}
            <form action="{% url 'news:search_news' 1 %}" method="get" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" name="key_value" type="text" placeholder="请输入关键字" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
            </form>
        </div>
    </nav>
{% endblock %}
{% block contentOther %}
{% endblock %}
{% block script %}{% endblock %}

templates/outlandnews.html
{#国际时事结果页#}
{% extends 'navicate.html' %}
{% load static %}
{% block foreign %}
    text-primary disabled
{% endblock foreign %}
{% block contentOther %}
    <div class="col-8">
        <div class="list-group">
            {% if not data %}
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <h1 class="display-4">Not Found</h1>
                        <p class="lead">没有相关新闻</p>
                    </div>
                </div>
            {% else %}
                {% for i in postList %}
                    <a href="{% url 'news:detail' i.id %}" class="list-group-item list-group-item-action d-flex w-100">
                        <div class="mr-2">
                            <img src="/{{ MEDIA_URL }}{{ i.pic }}" width=100 height=50>
                        </div>
                        <div class="flex-fill">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1 font-weight-bold">{{ i.title }}</h5>
                                <small class="text-muted">{{ i.publish_data}}</small>
                            </div>
                            <p class="mb-1 text-truncate"></p>
                        </div>
                    </a>
                {% endfor %}
            {% endif %}

            <nav id="page-nav">
                {% if postList.has_previous %}
                    <a class="extend prev" rel="next" href="{% url 'news:outland' postList.previous_page_number %}">« Prev</a>
                {% endif %}
                {% for page in pageList %}
                    {% if currentNum == page %}
                        <span class="page-number current">{{ page }}</span>
                    {% else %}
                        <a class="page-number" href="{% url 'news:outland' page %}">{{ page }}</a>
                    {% endif %}
                {% endfor %}
                {% if postList.has_next %}
                    <a class="extend next" rel="next" href="{% url 'news:outland' postList.next_page_number %}">Next »</a>
                {% endif %}
            </nav>
        </div>
    </div>
{% endblock %}

templates/panorama.html
{# 新闻详情页动态填充数据 #}
{% extends 'navicate.html' %}
{% load static %}
{% block contentOther %}
    <div>
        {% for foo in new %}
            <div class="alert alert-success" role="alert">
                <h4 class="alert-heading" align="center">{{ foo.title }}</h4>
                <hr>
                <h6 class="mb-0" align="right">{{ foo.publish_data }}</h6>
            </div>
            <div class="" align="center">
                <img src="/{{ MEDIA_URL }}{{ foo.pic }}" class="img-fluid" alt="{{ foo.title }}">
            </div>
            <div class="">
                <div class="card-body" align="center">
                    {{ foo.content|safe }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block script %}
{% endblock %}

templates/register.html
{# 注册功能实现 #}
{% extends 'navicate.html' %}
{% load static %}
{% block title %}登录{% endblock %}
{% block contentOther %}
    <div align="center">
        <div class="form-wrapper">
            <form method="post" action="{% url 'login:register' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                        {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="button-wrapper submit">
                    <input type="submit" value="注册"/>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{#{% block contentOther %}#}
{#    <div align="center">#}
{#        <form action="{% url 'login:login' %}" method="post">#}
{#            {% csrf_token %}#}
{#            <div class="form-group">#}
{#                <label for="exampleInputEmail1">用户名：</label><input type="text" name="name" required/>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <label for="exampleInputPassword1">密&emsp;码：</label><input type="password" name="pwd" required/>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <label for="exampleInputPassword1">再一次：</label><input type="password" name="pwd2" required/>#}
{#                <small id="emailHelp" class="form-text text-muted">请确保你两次输入的密码一致</small>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <label for="exampleInputPassword1">邮&emsp;箱：</label><input type="email" name="eml" required/>#}
{#            </div>#}
{#            <p>#}
{#                &emsp;&emsp;&emsp;&emsp;<input type="submit" value="注册"/>#}
{#            </p>#}
{#        </form>#}
{#    </div>#}
{##}
{#{% endblock contentOther %}#}